kind: Service
apiVersion: v1
metadata:
   name: jenkins-slave-service
   namespace: jenkins  
spec:
  selector:
    app: jenkins-agent
  ports:
   - protocol: TCP
     port: 22
     targetPort: 22   


